version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dogapp
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5434:5432
    volumes:
      - ./postgress_dog_app:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5052:80


  django:
    build:
      context: .
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=dogapp
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres