# Generated by Django 4.2.5 on 2023-09-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
