# Generated by Django 4.2.5 on 2024-06-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pet_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_photo', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.IntegerField()),
                ('portada', models.IntegerField()),
            ],
        ),
    ]
