# Generated by Django 4.2.5 on 2024-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vet_petphotos_pet_veterinarian_petshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshare',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
